### PR TITLE
Update analytics snippet to use baseurl

### PR DESCRIPTION
**Pull request by praseodym**

### CODE REVIEW

**Comment by barryclark** [comment]
Doesn't look like specifying the page and title are really needed any more at all - ref: https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by praseodym** [comment]
I think it was never mandatory, but apparently it can improve the analytics quality, as noted in 9f23e44cbeb6555d5a0afd9d624e515e661a9c19.

**Comment by barryclark** [comment]
Ahh yes. Thanks for the reminder.

Looks like it doesn't need {{ site.baseurl }} though? It appears that you're just supposed to send the path, excluding the domain.

**Comment by praseodym** [comment]
The Google Analytics interface links back to the path, which doesn't work correctly with the baseurl; you'll get `example.com/page.html` instead of `example.com/blog/page.html` if `blog` is your baseurl.

**Comment by barryclark** [comment]
I see. That's right. Thanks Mark!

**Comment by praseodym** [comment]
Cheers!

**Comment by barryclark** [comment]
:beers:

**Pull request merged**
