### PR TITLE
Add editorconfig

### PR DESCRIPTION
**Pull request by mediadoneright**
Update editorconfig to match Jekyll

There is [a pull-request for the Jekyll project (#3527)](jekyll/jekyll#3527) for a similar editorconfig file.  This change synchronizes the file between projects.

@barryclark you may wish to hold off on a decision to merge based on results of Jekyll pull request, but thought I'd update here just in case you got around to it first.

### CODE REVIEW

**Comment by mediadoneright** [comment]
My workflow was a little wonky on this.  In case it helps, here is a reference to the [original pull request with rationale](/mediadoneright/jekyll-now/pull/1) from my repo's issue queue.

**Comment by barryclark** [comment]
Thanks for pushing forward on suggesting this, Mike.

After a lot of thought I've decided not to add the ```.editorconfig```. The main reason is that I'm trying to keep the number of files and line code in the repository to a minimum making it as easy as possible for people to use and understand. Every extra file or line of code in the repository is more overhead for people to understand. 

If I were merging a higher volume of pull requests, like a huge project like Ruby or GitHub, then I think it'd be worth it then. But with only 1 PR merged per month or so I'll just be more strict in enforcing coding standards in PRs before merging them.

**Comment by mediadoneright** [comment]
yep, no worries.  thanks for sharing your rationale

**Comment by barryclark** [comment]
Thanks for sharing your suggestions. I like having these types of tradeoffs discussions—leads to a better project for everyone!

**Pull request closed without merging**
