### PR TITLE
Ja era hora

### PR DESCRIPTION
**Pull request by AlexChicote**

### CODE REVIEW

**Comment by AlexChicote** [comment]
Ben fet

**Comment by AlexChicote** [comment]
No cal

**Comment by AlexChicote** [comment]
A veure si funciona

**Comment by AlexChicote** [comment]
Aprenent cada dia una mica

**Comment by JOJ0** [comment]
Hi AlexChicote, I can't imagine that you want to merge 164 commits to the jekyll-now repo. What are you intending to do? Maybe you only want ot merge 1 new feature/commit from your repo? If yes you did it wrong. Please follow these guidelines: https://gist.github.com/vlandham/3b2b79c40bc7353ae95a.
Hope that helps!
all the best
Jojo

**Comment by JOJ0** [comment]
Hi, each and every commit you do in your master branch lands in this pull request. Is this really what you want to do? I think it is best you close this pull request.
all the best
Jojo

**Comment by AlexChicote** [comment]
Done.Thank you


________________________________

**Pull request closed without merging**
