### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by mrs-requies**

### CODE REVIEW

**Comment by jpasholk** [comment]
I believe this was made in error. Looks like personal changes to me.

**Comment by mrs-requies** [comment]
True that. Can I somehow reset this?

⁣Gesendet mit Blue ​

**Comment by jpasholk** [comment]
@mrs-requies Yeah, you should be able to close the pull request yourself if you're the one who opened it.

[Check this out](https://help.github.com/articles/closing-a-pull-request/)

[And this.](https://stackoverflow.com/questions/5385567/how-to-cancel-a-pull-request-on-github/10142727)

:)

**Comment by mrs-requies** [comment]
I believe I fixed it, did I? :)

**Pull request closed without merging**
