### PR TITLE
disqus_identifier param is not used

### PR DESCRIPTION
**Pull request by daattali**

### CODE REVIEW

**Comment by barryclark** [comment]
Hey @daattali,

Did you set your identifier in the ```_config.yml``` here? https://github.com/barryclark/jekyll-now/blob/master/_config.yml#L33-L35

That's where it gets pulled in from.

**Comment by daattali** [comment]
Thanks for taking a look so quickly.

The `disqus.html` template does indeed use `site.disqus`, but the `post.html` is passing another parameter as well  - `disqus_identifier`, and I don't see that being used anywhere.  Maybe it's a variable that automagically makes something work, otherwise I don't see why it's needed.

**Comment by barryclark** [comment]
I must be drunk :beer: I mistakenly thought that you'd added ```disqus_identifier```. Thanks for the fix!

**Comment by daattali** [comment]
a little too early for that on the west coast, but it's good to hear some of us are having a good weekend :)

**Comment by barryclark** [comment]
:smile: Thanks again for the fix, Dean!

**Pull request merged**
