### PR TITLE
Follow standards

### PR DESCRIPTION
**Pull request by LeoColomb**
All is in the title, and please see the commit log for details.

:nail_care:

### CODE REVIEW

**Comment by mediadoneright** [comment]
I just reviewed ... and my two cents .... this should get committed sooner than later. It'll take you @barryclark  5-10minutes.  Not much here besides clean-up & goodness.

What I found, white-space stripped from files (partly why so many files touched, but easy to eyeball changes).  Also a couple consistency fixes for things like double quotes.  Also a default `EditorConfig` file (totally needed for collaboration/standardization).

Of note, *(that would have personally saved me at least 2hrs of learning crap I never needed to know, and probably why I'm perusing the issue queue now)* is the standardization of sass setup. I wish this had been committed last year before I tried out the project.  ;-)

**Comment by LeoColomb** [comment]
@mediadoneright Thanks for your review!

**Comment by barryclark** [comment]
I hear you @LeoColomb & @mediadoneright. The reason I hadn't merged this yet is because there are a number of different things going on in the PR, not all of which I was sure I wanted to merge in. That and I couldn't auto-merge it.

Whitespace fixed by https://github.com/barryclark/jekyll-now/commit/f3ce4344d1d5d5cdf3212ba0e0d07cc1ba26bdea -- taking a look at the other bits now.

**Comment by barryclark** [comment]
I think I got everything with the commits above. Passing on EditorConfig as I don't think it's necessary and adds a little bit of overhead in figuring it out.

Thanks +1000000 for the help @LeoColomb and @mediadoneright. Apologies it took a while getting around to fixing some of these things!

Please open separate issues/PRs for any additional stuff.

**Pull request closed without merging**
