### PR TITLE
Add Jekyll favicon

### PR DESCRIPTION
**Pull request by dijonkitchen**

### CODE REVIEW

**Comment by barryclark** [comment]
I really like this, Jonathan. Wanna update the PR with storing the icon file locally in the repo and referencing that? 

Then I'll merge this in.

That way if the URL ever changes on jekyllrb.com we won't have to worry about everyone's blog icons being broken :)

**Comment by dijonkitchen** [comment]
@barryclark Yes, I agree. It should be a relative reference if you want to store the favicon on the repo.

**Comment by barryclark** [comment]
@dijonkitchen wanna update the PR to add it, and I'll merge?

**Comment by cesards** [comment]
@dijonkitchen @barryclark What happens with this? Is it gonna be merged?

**Comment by dijonkitchen** [comment]
Sorry, been really busy. Feel free to do this yourself!

**Comment by cesards** [comment]
The only one who can merge this is @barryclark I'm afraid ;-)

**Comment by Chocobo1** [comment]
I've opened a PR #481 and added a commit after the initial commit by @dijonkitchen.

**Comment by dijonkitchen** [comment]
Closing in favor of #481 by @Chocobo1!

**Pull request closed without merging**
