### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mikeack**

### CODE REVIEW

**Comment by cesards** [comment]
@barryclark What's wrong with people? xD

**Comment by mikeack** [comment]
Yeah, I just noticed. Trying to get this thing up for the first time. Sorry :P

-- 
Mike Ackerman
Sent with Airmail

On February 1, 2016 at 3:12:07 PM, César Díez Sánchez (notifications@github.com) wrote:

@barryclark What's wrong with people? xD

**Comment by cesards** [comment]
Haha don't worry @mikeack . It was a joke, but people don't close the PR as you have done :-P and as you can see, you're not the only one! ^^ Enjoy Jekyll!

**Comment by mikeack** [comment]
Yeah, I was getting an email saying my site wouldn’t build so I started messing around trying to follow some of the troubleshooting steps and I think I pushed mine to the Master. I’m so sorry. LOL

-- 
Mike Ackerman
Sent with Airmail

On February 1, 2016 at 3:16:31 PM, César Díez Sánchez (notifications@github.com) wrote:

Haha don't worry @mikeack . It was a joke, but people don't close the PR as you have done :-P and as you can see, you're not the only one! ^^ Enjoy Jekyll!

**Comment by mikeack** [comment]
Well I started a new fork and lost all my files. New to GitHub. Time to recreate each of the files in the _posts folder :-/
-- 
Mike Ackerman
Sent with Airmail

**Comment by mikeack** [comment]
Any chance you can completely remove #402? It has a lot of personal info in there. Sorry to be just a bother :P

-- 
Mike Ackerman
Sent with Airmail

On February 1, 2016 at 3:17:20 PM, Mike Ackerman (mikeack@mac.com) wrote:

Yeah, I was getting an email saying my site wouldn’t build so I started messing around trying to follow some of the troubleshooting steps and I think I pushed mine to the Master. I’m so sorry. LOL

-- 
Mike Ackerman
Sent with Airmail

On February 1, 2016 at 3:16:31 PM, César Díez Sánchez (notifications@github.com) wrote:

Haha don't worry @mikeack . It was a joke, but people don't close the PR as you have done :-P and as you can see, you're not the only one! ^^ Enjoy Jekyll!

**Pull request closed without merging**
