### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by dijonkitchen**
Generalize logo

### CODE REVIEW

**Comment by barryclark** [comment]
What @Koxzi95 said. The idea is that it's easier for people to just link to an already existing avatar that's online, rather than uploading one.

A dynamic link is good too, but it's likely a little more work for people and the idea of Jekyll Now is that it's super fast/easy to set up.

Thanks!

**Comment by dijonkitchen** [comment]
I figured it would be easier. You already have a jekyll logo png in the images folder.

**Comment by barryclark** [comment]
Yep, that's a placeholder so that something shows there. The idea is that you add your own during the initial setup when you edit config.yml, rather than having to upload an image.

Both are cool really, I think linking to the avatar in config.yml is a bit easier for GitHub newbies.

**Comment by dijonkitchen** [comment]
Very well. Thanks for the feedback! Many more pull requests to go!

**Comment by barryclark** [comment]
Yea! I like the others you added. Just need to get around to testing  :)

**Pull request closed without merging**
